% THIS SCRIPT ASSUMES YOU HAVE IMPORTED DATA.CSV USING THE DEFAULT NAMES

TemperatureC = Temperature .* 0.49; % Converts the temperature ADC reading to degrees C
% See: http://www.ti.com/lit/ds/symlink/lm35.pdf

PressurekPa = ((Pressure .* .0049) + 0.2) / 0.009; % Converts pressure ADC reading to kPa
% See: http://cache.freescale.com/files/sensors/doc/data_sheet/MPX5500.pdf

ConductivityV = Conductivity .* .0049; % Convert to volts for now.


%  Auto-generated by MATLAB on 20-Apr-2014 12:14:24
% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'FontSize',14);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(Timestamp,TemperatureC,'Parent',axes1,'MarkerSize',3,'LineWidth',1);
plot2 = plot(Timestamp,PressurekPa,'Parent',axes1,'MarkerSize',3,'LineWidth',1);
plot3 = plot(Timestamp,ConductivityV,'Parent',axes1,'MarkerSize',3,'LineWidth',1);
set(plot1,'Marker','diamond','DisplayName','Temperature');
set(plot2,'Marker','square','DisplayName','Pressure');
set(plot3,'Marker','o','DisplayName','Conductivity');

% Create xlabel
xlabel('Time (ms)','FontSize',14);

% Create ylabel
ylabel('Temperature (degrees C), Pressure (kPa), Conductivity (S/m)',...
    'FontSize',14);

% Create title
title({'CTD Sensor Data'},'FontSize',24);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','Best');